[build]
builder = "nixpacks"
buildCommand = "composer install --optimize-autoloader --no-dev && php artisan config:cache && php artisan route:cache"

[deploy]
startCommand = "php artisan serve --host=0.0.0.0 --port=$PORT"
healthcheckPath = "/api"
healthcheckTimeout = 100

[variables]
PHP_VERSION = "8.2"
